"""Public synthetic fixtures verify compatibility with the previous JWT library."""

import os
import unittest
from unittest.mock import patch

os.environ.setdefault("APP_ENV", "test")
os.environ.setdefault("SECRET_KEY", "synthetic-jwt-test-key-with-at-least-32-bytes")
os.environ.setdefault("DATABASE_URL", "postgresql://unused:unused@127.0.0.1:1/synthetic")

import jwt
from fastapi import HTTPException
from app.core.config import settings
from app.core.security import create_access_token, decode_token
from app.services import storage_service as storage

KEY = "synthetic-jose-compatibility-key-not-a-secret"
# Generated by python-jose 3.3.0 using the public key above; no real account.
JOSE_ACCESS = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9."
    "eyJzdWIiOiIxMjMiLCJleHAiOjQxMDI0NDQ4MDAsImlhdCI6MTcwNDA2NzIwMCwiaXNzIjoibXV2di1hcGkiLCJhdWQiOiJtdXZ2LWFwcCIsInRva2VuX3R5cGUiOiJhY2Nlc3MiLCJyb2xlIjoiY2xpZW50In0."
    "C4OuqEyW4T3PcY-6WnlA_uGzCfWvDThWDyqwrQUxtLw"
)
JOSE_DOCUMENT = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9."
    "eyJwdXJwb3NlIjoiZHJpdmVyX2RvY3VtZW50X3ZpZXciLCJkcml2ZXJfaWQiOjcsImRvY3VtZW50X3R5cGUiOiJsaWNlbnNlX2ltYWdlIiwiZG9jdW1lbnRfcmVmIjoiZHJpdmVycy83L3N5bnRoZXRpYy5qcGciLCJleHAiOjQxMDI0NDQ4MDB9."
    "GcJekIViCx3I1VEhVS_lS1-sjrFw6xlgtkLSx6IJYVA"
)
PRIVATE_CASES = (
    (storage.create_driver_document_view_token, storage.decode_driver_document_view_token,
     (7, "license_image", "drivers/7/synthetic.jpg"), storage.DOCUMENT_VIEW_PURPOSE),
    (storage.create_freight_evidence_view_token, storage.decode_freight_evidence_view_token,
     (9, "delivery", "freights/9/synthetic.jpg"), storage.FREIGHT_EVIDENCE_VIEW_PURPOSE),
    (storage.create_cargo_photo_view_token, storage.decode_cargo_photo_view_token,
     (9, 12, "freights/9/cargo/synthetic.jpg"), storage.CARGO_PHOTO_VIEW_PURPOSE),
    (storage.create_chat_image_view_token, storage.decode_chat_image_view_token,
     (9, 13, "freights/9/chat/synthetic.jpg"), storage.CHAT_IMAGE_VIEW_PURPOSE),
)


class JwtCompatibilityTests(unittest.TestCase):
    def setUp(self):
        self.enterContext(patch.object(settings, "SECRET_KEY", KEY))
        self.enterContext(patch.object(settings, "JWT_ISSUER", "muvv-api"))
        self.enterContext(patch.object(settings, "JWT_AUDIENCE", "muvv-app"))

    def denied(self, decode, token, status):
        with self.assertRaises(HTTPException) as error:
            decode(token)
        self.assertEqual(error.exception.status_code, status)

    def claims(self):
        return decode_token(create_access_token({"sub": "123", "role": "client"}))

    def test_existing_jose_access_and_document_remain_valid(self):
        self.assertEqual(decode_token(JOSE_ACCESS)["sub"], "123")
        self.assertEqual(storage.decode_driver_document_view_token(JOSE_DOCUMENT)["driver_id"], 7)

    def test_required_claims(self):
        for field in ("exp", "iat", "iss", "aud", "sub", "token_type"):
            with self.subTest(field=field):
                claims = self.claims()
                del claims[field]
                self.denied(decode_token, jwt.encode(claims, KEY, algorithm="HS256"), 401)

    def test_invalid_claim_types_issuer_audience_and_times(self):
        for field, value in (("exp", 1), ("exp", []), ("iat", {}), ("sub", 123),
                             ("iss", "other"), ("aud", "other"), ("iat", 4102444800)):
            with self.subTest(field=field, value=value):
                claims = self.claims()
                claims[field] = value
                self.denied(decode_token, jwt.encode(claims, KEY, algorithm="HS256"), 401)

    def test_wrong_algorithm_unsigned_and_signature(self):
        claims = self.claims()
        for token in (jwt.encode(claims, KEY * 2, algorithm="HS384"),
                      jwt.encode(claims, "", algorithm="none"),
                      jwt.encode(claims, "another-synthetic-key-at-least-32-bytes", algorithm="HS256")):
            self.denied(decode_token, token, 401)

    def test_private_round_trip_and_purpose_isolation(self):
        access = create_access_token({"sub": "123"})
        for create, decode, args, purpose in PRIVATE_CASES:
            token, _ = create(*args)
            self.assertEqual(decode(token)["purpose"], purpose)
            self.denied(decode_token, token, 401)
            for _, other_decode, _, other_purpose in PRIVATE_CASES:
                self.denied(other_decode, access, 404)
                if purpose != other_purpose:
                    self.denied(other_decode, token, 404)

    def test_private_expiry_and_purpose_required(self):
        for create, decode, args, purpose in PRIVATE_CASES:
            original = decode(create(*args)[0])
            for change in ("expired", "missing", "purpose"):
                with self.subTest(purpose=purpose, change=change):
                    claims = original.copy()
                    if change == "expired":
                        claims["exp"] = 1
                    elif change == "missing":
                        del claims["exp"]
                    else:
                        claims["purpose"] = "other"
                    self.denied(decode, jwt.encode(claims, storage._view_token_key(purpose), algorithm="HS256"), 404)

    def test_malformed_tokens_have_generic_errors(self):
        for token in ("", "not.jwt", "a.b.c", "[]", "e30.W10.invalid"):
            self.denied(decode_token, token, 401)
            for _, decode, _, _ in PRIVATE_CASES:
                self.denied(decode, token, 404)
